### ISSUE TITLE
README.md client/server seem switched

### ISSUE THREAD

**Issue by mumbleskates** [jedisct1/fastly-terrarium-examples#1]
The diagrams showing protocol exchanges between client and server for registration and authentication seem to only make sense if `{client}` were on the left and `{server}` were on the right, but they are switched. Am I misunderstanding something?

Additionally, the final transmission in authentication sending `V(pk, (domain || username || nonce))` should probably be `V(s, (domain || username || nonce), pk)` -- assuming this is meant to be a boolean success/fail response for the authentication exchange from the server to the client.

**Comment by jedisct1** [comment]
Good catch, thank you!

This has been fixed.
